### ISSUE TITLE
Edge version doesn't launch anymore (fatal: can only run as pid 1)

### ISSUE THREAD

**Issue by thardie** [zigbee2mqtt/hassio-zigbee2mqtt#335]
**Description of problem:**
Edge version fails to launch

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Edge
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.2.9
Supervisor: supervisor-2022.05.1
Operating System: Home Assistant OS 7.4
```

**Your logs from Home Assistant Supervisor**
```
s6-overlay-suexec: fatal: can only run as pid 1
```

**Comment by arnesweb** [comment]
> **Description of problem:** Edge version fails to launch
> 
> **Zigbee2mqtt add-on version (if edge, please report commit hash):**
> 
> ```
> Edge
> ```
> 
> **Running platform (details from Suypervisor > System)**
> 
> ```
> Core: core-2022.2.9
> Supervisor: supervisor-2022.05.1
> Operating System: Home Assistant OS 7.4
> ```
> 
> **Your logs from Home Assistant Supervisor**
> 
> ```
> s6-overlay-suexec: fatal: can only run as pid 1
> ```

I have the exact same problem with Edge version,

**Comment by schiz0phr3ne** [comment]
Same here.

Seems to be caused by HA update to the last S6-overlay version, check here : https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by thardie** [comment]
Adding `init: false` to the config.json (in correct json format) also leads to other subsequent failures. Even though it fixes the initial error, all the other shell scripts for startup don't work (Permission Denied). I tried changing them to +x in the git repo, and trying the recommended apparmor.txt but still get permission denied, so I gave up.

**Comment by jctovilla** [comment]
I have the same problem:

Zigbee2mqtt Edge  s6-overlay-suexec  fatal  can only run as pid 1

**Comment by chrisrock1984** [comment]
any news on that? having the same issue!

**Comment by smulle48** [comment]
same here

**Comment by tranrn** [comment]
Same

**Comment by eladiogalvez** [comment]
Same here

**Comment by mdegat01** [comment]
Figured it out. So the steps in the blog are still valid for fixing this addon, add `init: false` and modify files to be executable.

The extra problem is that this addon doesn't have a `build.yaml` file and isn't pinning the version of its base image. Latest for the [alpine base image](https://github.com/home-assistant/docker-base) is now 3.15 and this addon doesn't work on 3.15. It needs a `build.yaml` pinning the version to 3.14 until the application an be updated to work on 3.15. This part isn't related to s6 v3 it just happened to bite at the same time. I'll put in a PR for all the above.

**Comment by thardie** [comment]
> Figured it out. So the steps in the blog are still valid for fixing this addon, add `init: false` and modify files to be executable.
> 
> The extra problem is that this addon doesn't have a `build.yaml` file and isn't pinning the version of its base image. Latest for the [alpine base image](https://github.com/home-assistant/docker-base) is now 3.15 and this addon doesn't work on 3.15. It needs a `build.yaml` pinning the version to 3.14 until the application an be updated to work on 3.15. This part isn't related to s6 v3 it just happened to bite at the same time. I'll put in a PR for all the above.

I pulled your PR into my repo (https://github.com/thardie/hassio-zigbee2mqtt) and it doesn't work for me. Did I mess something up? Here's my startup log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/socat.sh: Permission denied
cont-init: info: /etc/cont-init.d/socat.sh exited 126
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/zigbee2mqtt.sh: Permission denied
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mdegat01** [comment]
@thardie in your fork you still list the same [image](https://github.com/thardie/hassio-zigbee2mqtt/blob/master/zigbee2mqtt-edge/config.json#L71) as the one here. So your fork isn't really testing anything, you're just using whichever one of [these images](https://hub.docker.com/search?q=zigbee2mqtt%2Fzigbee2mqtt-edge&type=image) matches your architecture.

To test the branch you would have to pull it into your `/addons` folder and merge the `common` folder and `zigbee2mqtt` or `zigbee2mqtt-edge` folders to make a normal addon that supervisor can build an image for. Or you'd have to adjust the CI in your fork so you can actually publish your own images to dockerhub and use them.

**Comment by thardie** [comment]
> @thardie in your fork you still list the same [image](https://github.com/thardie/hassio-zigbee2mqtt/blob/master/zigbee2mqtt-edge/config.json#L71) as the one here. So your fork isn't really testing anything, you're just using whichever one of [these images](https://hub.docker.com/search?q=zigbee2mqtt%2Fzigbee2mqtt-edge&type=image) matches your architecture.
> 
> To test the branch you would have to pull it into your `/addons` folder and merge the `common` folder and `zigbee2mqtt` or `zigbee2mqtt-edge` folders to make a normal addon that supervisor can build an image for. Then remove `image` from the `config.json` so supervisor does build a new image and doesn't just use the one from dockerhub. Or you'd have to adjust the CI in your fork so you can actually publish your own images to dockerhub and then adjust the `config.json` to use them.

Sorry to be a PITA. I've updated my repo and built all the images and loaded them into my own docker registry (orcas.docker-public.orcas.net). I've verfied I can `docker pull` them anonymously, but my HA won't take the update:

```
22-05-17 00:24:58 WARNING (SyncWorker_7) [supervisor.store.data] Can't read /data/addons/git/3be6726f/zigbee2mqtt-edge/config.json: does not match regular expression ^([a-zA-Z\-\.:\d{}]+/)*?([\-\w{}]+)/([\-\w{}]+)$ for dictionary value @ data['image']. Got 'orcas.docker-public.orcas.net/zigbee2mqtt-edge-{arch}'
```
I also tried your other suggestion of loading it into my addons and merging the folders, but that fails when I try to add the addon with:
```
22-05-17 00:17:40 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/local_zigbee2mqtt_edge
22-05-17 00:17:40 ERROR (SyncWorker_5) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```

**Comment by mdegat01** [comment]
@thardie So I'm not sure why exactly its coded this way but this is the regex for `image` from that error:
```
^([a-zA-Z\-\.:\d{}]+/)*?([\-\w{}]+)/([\-\w{}]+)$
```
`orcas.docker-public.orcas.net/zigbee2mqtt-edge-{arch}` doesn't pass that regex because it's only got one resource path part. For example if it was this `orcas.docker-public.orcas.net/a/zigbee2mqtt-edge-{arch}` then it would work. It just really wants a second path part.

I can't really explain why here, I was kind of cringing why I typed it to be honest. I guess I've got to look into that. For now, I can only tell you what the regex does lol.

> I also tried your other suggestion of loading it into my addons and merging the folders, but that fails when I try to add the addon with:

I'm not sure how to explain this one. I tried it just now starting from a blank `/addons` folder on a dev system and had no issues. First I did this:
```
> git clone --depth 1 -b base-image-s6-v3-update https://github.com/mdegat01/hassio-zigbee2mqtt
> mv hassio-zigbee2mqtt/common/* hassio-zigbee2mqtt/zigbee2mqtt-edge
```
Then I removed `image` from `config.json` in the `zigbee2mqtt-edge` folder. Then I went to the [addon store](https://my.home-assistant.io/redirect/supervisor_store/), clicked the 3 dots in the upper right and did "Check for updates" to make my new local addon appear. I installed the edge version (it built fine) and then ran it, got this in the log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/socat.sh
[16:44:24] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0
cont-init: info: running /etc/cont-init.d/zigbee2mqtt.sh
cont-init: info: /etc/cont-init.d/zigbee2mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun socat (no readiness notification)
services-up: info: copying legacy longrun zigbee2mqtt (no readiness notification)
[16:44:26] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
Zigbee2MQTT:info  2022-05-17 16:44:29: Logging to console and directory: '/config/zigbee2mqtt/log/2022-05-17.16-44-28' filename: log.txt
Zigbee2MQTT:info  2022-05-17 16:44:29: Starting Zigbee2MQTT version 1.25.1-dev (commit #5ae8347)
Zigbee2MQTT:info  2022-05-17 16:44:29: Starting zigbee-herdsman (0.14.31)
Zigbee2MQTT:error 2022-05-17 16:44:29: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-05-17 16:44:29: Failed to start zigbee
Zigbee2MQTT:error 2022-05-17 16:44:29: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-05-17 16:44:29: Exiting...
Zigbee2MQTT:error 2022-05-17 16:44:30: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
```

I mean to be clear the addon isn't working here because I don't actually have a zigbee coordinator plugged into my dev system right now and didn't configure the addon at all. But it is running all the start-up scripts successfully so it would work with a real config and a coordinator.

**Comment by thardie** [comment]
Thanks for the response, I really appreciate it. I couldn't understand why the regex wasn't matching, since I was barking up this tree:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> res = '^([a-zA-Z\-\.:\d{}]+/)*?([\-\w{}]+)/([\-\w{}]+)$'
>>> re.match(res, "foo/bar")
<re.Match object; span=(0, 7), match='foo/bar'>
>>> re.match(res, "foo.a/bar")
>>>
```
I was convinced it was in the first part (periods in the domain name) and couldn't understand why. Thanks for helping with that.

As for the addons folder, I'll work on that - I'll just assume something's gorked in my HAOS that can't build locally for some reason not related to this addon.

I'll re-organize my repo so there's an additional directory. Thanks again.

**Comment by thardie** [comment]
I've managed to get it running. All seems good (Zigbee is working), but the web frontend doesn't work. I see this error in the logs:
```
(node:166) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
    at check (/app/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
    at Frontend.gzipStatic (/app/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

Should I open a new issue?

**Comment by mdegat01** [comment]
@thardie I think that might just be a frontend bug in Z2M. I found [this](https://github.com/nurikk/zigbee2mqtt-frontend/issues/1480), looks the same. It is still the edge version so that can happen.

**Comment by nurikk** [comment]
Problem localised, buggy dependency got downgraded

https://github.com/pirxpilot/connect-gzip-static/issues/16

**Comment by DavyRoswinkel** [comment]
Having the same issue, using edge c6840a9a435f9c2da1fd2fdc611249fb58b10d92

Description of problem:
```
Addon doesn't start, trying to open the UI gives 502 bad gateway
Tried restoring a backup but the error stays
Zigbee2mqtt logs show:
s6-overlay-suexec: fatal: can only run as pid 1
```

Zigbee2mqtt add-on version (if edge, please report commit hash):

`edge c6840a9a435f9c2da1fd2fdc611249fb58b10d92`

Your entire configuration from the frontend (with sensitive fields redacted):

```
data_path: /share/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://192.168.1.55:1883
  user: ****
  password: ****
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2403707-if00
  adapter: deconz
```

Running platform (details from Suypervisor > System)

```
core-2022.5.4
Home Assistant OS 8.0
supervisor-2022.05.2
```


Your logs from Home Assistant Supervisor

```
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/net-daemon/homeassistant-addon repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons/ repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Expaso/hassos-addons repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/MaxWinterstein/homeassistant-addons repository
22-05-18 15:39:11 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sanderdw/hassio-addons repository
22-05-18 15:39:14 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-05-18 15:39:15 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-05-18 15:39:15 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-05-18 15:39:16 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-05-18 15:39:16 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-05-18 15:39:16 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-05-18 15:39:17 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:39:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 158 all - 0 new - 0 remove
22-05-18 15:39:19 INFO (MainThread) [supervisor.store] Loading add-ons from store: 158 all - 0 new - 0 remove
22-05-18 15:39:26 ERROR (SyncWorker_2) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:39:47 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:39:48 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:39:49 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 0.0.0.0:8099 ssl:default [Connect call failed ('0.0.0.0', 8099)]
22-05-18 15:39:50 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:40:04 ERROR (SyncWorker_3) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:40:20 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:40:20 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:40:22 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:40:31 ERROR (SyncWorker_5) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:40:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 1e14b3fb_tgtg-ha-mqtt-bridge!
22-05-18 15:40:52 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_1e14b3fb_tgtg-ha-mqtt-bridge application
22-05-18 15:40:52 ERROR (SyncWorker_3) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:40:53 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64 with version 2.0.0
22-05-18 15:40:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:40:53 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:40:55 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:41:00 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'TestUser'
22-05-18 15:41:00 INFO (MainThread) [supervisor.auth] Home Assistant not running, checking cache
22-05-18 15:41:25 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:41:26 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:41:27 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:41:58 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:41:58 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:42:00 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:42:30 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:42:30 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:42:32 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:43:02 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:43:02 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:43:04 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:43:06 ERROR (SyncWorker_3) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:43:11 ERROR (SyncWorker_5) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:43:38 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:43:39 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:43:44 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:43:57 WARNING (SyncWorker_2) [supervisor.docker.interface] Can't grep logs from zigbee2mqtt/zigbee2mqtt-edge-aarch64: 404 Client Error for http+docker://localhost/v1.41/containers/ccd804f02ab52d82ffc5fc71d5b0be3861f16891b9c04ae2a6a58cb775d6f2ae/json: Not Found ("No such container: ccd804f02ab52d82ffc5fc71d5b0be3861f16891b9c04ae2a6a58cb775d6f2ae")
22-05-18 15:44:14 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:44:14 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:44:15 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:44:35 ERROR (SyncWorker_0) [supervisor.docker.interface] Container addon_45df7312_zigbee2mqtt_edge is not running
22-05-18 15:44:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:44:46 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:44:47 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:45:18 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:45:18 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:45:19 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:45:48 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-05-18 15:45:49 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:45:49 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:45:51 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:46:21 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:46:22 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:46:23 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:46:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:46:53 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:46:55 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:47:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
22-05-18 15:47:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-05-18 15:47:13 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-05-18 15:47:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-05-18 15:47:13 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon
22-05-18 15:47:25 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:47:25 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge application
22-05-18 15:47:27 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
22-05-18 15:47:32 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-05-18 15:47:32 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-05-18 15:47:58 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 45df7312_zigbee2mqtt_edge!
22-05-18 15:47:59 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt_edge applica
```

**Comment by dtalens** [comment]
Same here

**Comment by migor7** [comment]
Same here

**Comment by tipunov-ao** [comment]
I have the same problem too

![Снимок экрана 2022-05-19 в 12 13 55](https://user-images.githubusercontent.com/64776317/169258435-2be9cb2e-5d0c-4101-b5f2-97d56254d8d4.png)

**Comment by coom** [comment]
Same here, cannot run the Edge version so I've switched to the main branch, but get some devices that aren't recognized.

Waiting for the fix, thank for your awesome work guys.

**Comment by bendiger** [comment]
Same error for me as well, I updated to hass OS version 8 and then this error after reboot. Didn't update my hass version yet, still on 2022.4.2.

**Comment by sator86** [comment]
same thing .....
any solution please ?

**Comment by schiz0phr3ne** [comment]
I finally choosen to run Z2M in a LXC container, in my Proxmox : no imcompability, and I can now use newest devices that was not supported nattively.

Good luck all

**Comment by Pro-Control** [comment]
Hyperion.NG
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by DJTerentjev** [comment]
Same problem...

**Comment by schiz0phr3ne** [comment]
> Likely enough ppl with same problem by now, but... here, too ^^ Went back to stable for now.

This is why I get off this add-on : Edge is not updated frequently, and Stable is outdated - out of the box - for some of my devices (Aqara WRS-R02 and Nous A1Z).

**Comment by jimmi1982** [comment]
Having the same issue. has anyone managed to fix this, if so could they provide some simple steps, couldn't follow previous comments or blog post. 

Any help greatly appreciated.

**Comment by thardie** [comment]
> Having the same issue. has anyone managed to fix this, if so could they provide some simple steps, couldn't follow previous comments or blog post.
> 
> Any help greatly appreciated.

The fix is not simple, but if you want to use the edge version I fixed, point your HA repo to https://github.com/thardie/hassio-zigbee2mqtt and install the edge version. I will not be keeping this up to date, so as soon as this is fixed upstream, you will need to switch back.

**Comment by dreimer1986** [comment]
> > Likely enough ppl with same problem by now, but... here, too ^^ Went back to stable for now.
> 
> This is why I get off this add-on : Edge is not updated frequently, and Stable is outdated - out of the box - for some of my devices (Aqara WRS-R02 and Nous A1Z).

Edge needs to be updated manually and is always recent. This is explained in the Addon information btw. Stable is... Stable

**Comment by schiz0phr3ne** [comment]
> Edge needs to be updated manually and is always recent. This is explained in the Addon information btw. Stable is... Stable

For sure.

But as you saw, Edge add-on was updated 10 days after this issue (PR was merged 19h ago).
Stable version is 1.18.x, which is dated from 05/2021 : seems to be a little bit outdated to me.

But, be sure I don't denigrate the amazing work of Koenkk and others : without, no Z2M.

**Comment by tranrn** [comment]
> It doesn't work for me, same error. Am I alone in this case?

Works fine for me.

**Comment by DJBenson** [comment]
> > It doesn't work for me, same error. Am I alone in this case?
> 
> Works fine for me.

Did you do anything special?

I've switched back to stable for now and when I installed edge again it still failed with the same error.

**Comment by dtalens** [comment]
Same issue with latest zigbee2mqtt edge digest [2b2120afbd9e](https://hub.docker.com/r/zigbee2mqtt/zigbee2mqtt-edge-amd64/tags)

**Comment by mdegat01** [comment]
FYI edge should work now. There was an issue with the config.json since my PR targetted the dev branch but master wasn't changed. Koenkk fixed that with #344 . I just tried installing and running edge and it worked without issue after that.

**Comment by mdegat01** [comment]
You probably need to go to the go to the [addon store](https://my.home-assistant.io/redirect/supervisor_store/) and click "check for updates". Then follow the normal updating process for the edge addon (reinstalling it I believe).

**Comment by Stef42300** [comment]
> You probably need to go to the go to the [addon store](https://my.home-assistant.io/redirect/supervisor_store/) and click "check for updates" in the menu in the top right. Then follow the normal updating process for the edge addon (reinstalling it I believe).

Yes I delete the zigbee2mqtt folder on my NUC and I reinstalled it. It works but my Danfoss devices are not supported...I don't understand why because it works perfectly before...

**Comment by thardie** [comment]
> > You probably need to go to the go to the [addon store](https://my.home-assistant.io/redirect/supervisor_store/) and click "check for updates" in the menu in the top right. Then follow the normal updating process for the edge addon (reinstalling it I believe).
> 
> Yes I delete the zigbee2mqtt folder on my NUC and I reinstalled it. It works but my Danfoss devices are not supported...I don't understand why because it works perfectly before...

Are you using my version? I'm not keeping it up to date with edge - I built it just after this problem started. When was support added to edge of Z2M for your Danfoss devices?

**Comment by thardie** [comment]
I just checked and getting from this official repo and installing the edge version now work (above commit fixed it for me)

**Comment by fishbone-git** [comment]
no luck here.  still fatal error

**Comment by thardie** [comment]
> > Are you using my version? I'm not keeping it up to date with edge - I built it just after this problem started. When was support added to edge of Z2M for your Danfoss devices?
> 
> I installed the version fixed on the official repo. My devices are recognized before...but not now https://www.zigbee2mqtt.io/devices/014G2461.html

Are you installing edge from the official repo?

**Comment by fishbone-git** [comment]
I had to uninstall, remove the repository, reboot the host the add repo and install.  Now it works.

**Comment by fredericomcorda** [comment]
Just tested, it's working (please follow the instructions when updating)

**Comment by dtalens** [comment]
Thanks, last Z2M edge commit is working!

**Comment by Mecallie** [comment]
I know this topic is closed, but I am still having the exact same error. I have uninstalled both the normal AND the edge add-ons, removed the repository from HA (after a reboot), added the repo and installed z2m again. The normal version is still working. The edge version still gives me the above error?

**Comment by smpillai11** [comment]
I have the same error  for latest version of edge - s6-overlay-suexec: fatal: can only run as pid 1
