### ISSUE TITLE
Current Products Hybrid ewand Gen 2 - State in HA showing unknown

### ISSUE THREAD

**Issue by shanelord01** [zigbee2mqtt/hassio-zigbee2mqtt#359]
### Description of the issue

Supported device: https://www.zigbee2mqtt.io/devices/CP180335E-01.html

In dev tools in HA, the blind is showing the state as below:
![Screenshot 2022-07-09 160334](https://user-images.githubusercontent.com/49434655/178094063-b51e620a-8611-4a9d-a64d-e63461c1cb10.jpg)

Entity:
Blinds - Back Lounge 1

State: 
unknown	

State attributes (YAML, optional):
current_tilt_position: 100
battery: 51
linkquality: 255
tilt: 100
friendly_name: Blinds - Back Lounge 1
supported_features: 240

This means it is not possible to use an open or close command in automations (instead you have to use "set blinds tilt position").

It also means when sharing to Homekit, Google Home or Alexa, the tap to open close, and tap-hold to slide to tilt position is not made available, nor are you shown current open or closed state.

Need to translate the current_tilt_position to open / close states in HA, ie 100 = OPEN, 0 = CLOSED, increasing from 0-99 = OPENING and decreasing from 100-1 = CLOSING.

Thanks.

### Addon version

1.26.0-1

### Platform

Core: core-2022.7.2
Supervisor: supervisor-2022.07.0
Operating System: Home Assistant OS 8.2

**Comment by Koenkk** [comment]
Do I understand correctly that this device only supports tilt and not position like normal covers do?

**Comment by shanelord01** [comment]
I can’t say I’m an expert on this. 

I know that the Hubitat support for this allows open close commands as well as tilt position. Not sure how they do this.

**Comment by Koenkk** [comment]
What happens when you set the `state` to open/close via the z2m frontend -> click on your device -> exposes tab?

**Comment by shanelord01** [comment]
> What happens when you set the `state` to open/close via the z2m frontend -> click on your device -> exposes tab?

My apologies for the delay. The OPEN/CLOSE buttons in the expose tab of Z2M for it work as expected.

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    cover_position_tilt: {
        cluster: 'closuresWindowCovering',
        type: ['attributeReport', 'readResponse'],
        options: [exposes.options.invert_cover()],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            // Zigbee officially expects 'open' to be 0 and 'closed' to be 100 whereas
            // HomeAssistant etc. work the other way round.
            // For zigbee-herdsman-converters: open = 100, close = 0
            // ubisys J1 will report 255 if lift or tilt positions are not known, so skip that.
            const invert = model.meta && model.meta.coverInverted ? !options.invert_cover : options.invert_cover;
            if (msg.data.hasOwnProperty('currentPositionTiltPercentage') && msg.data['currentPositionTiltPercentage'] <= 100) {
                const value = msg.data['currentPositionTiltPercentage'];
                result.tilt = invert ? value : 100 - value;
                result.state = result.tilt === 0 ? 'CLOSE' : 'OPEN';
            }
            return result;
        },
    }
}

const definition = {
    zigbeeModel: ['E-Wand'],
    model: 'CP180335E-01',
    vendor: 'Current Products Corp',
    description: 'Gen. 2 hybrid E-Wand',
    fromZigbee: [fzLocal.cover_position_tilt, fz.battery],
    toZigbee: [tz.cover_state, tz.cover_position_tilt],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'closuresWindowCovering']);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.currentPositionTiltPercentage(endpoint);
    },
    exposes: [e.battery(), e.cover_tilt()],
};

module.exports = definition;
```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by shanelord01** [comment]
> Could you check if the issue is fixed with the following external converter:
> 

No change - but my steps just in case I've done something wrong:

1. Used Home Assistant addon "File Editor"
2. Created a file in the config/zigbee2mqtt/ folder next to configuration.yaml called ext_converter.js
3. Added the text exactly as above into this file, starting with "const fz = require" and finishing at "module.exports = definition;"
4. Saved that file
5. Edited the configuration,yaml file in the config/zigbee2mqtt/ folder
6. Added the external_converters section exactly as above.
7. Stopped Z2M. Started it again.
8. Hit the reconfigure button in Z2M for each blind
9. Hit OPEN then CLOSE on each blind
10. Checked the Entity State in Dev Tools - still shows unknown

Thanks.

**Comment by shanelord01** [comment]
I'm also seeing this in the logs:

```
2022-07-31T06:05:15.609Z zigbee-herdsman:deconz:adapter could not parse zclFrame: Error: Cluster '64528' has no command response '128'
2022-07-31T06:05:15.610Z zigbee-herdsman:controller:log Received 'raw' data '{"clusterID":64528,"data":{"type":"Buffer","data":[13,99,18,108,128,97,0,0,0,0,2,0,0,192,39,18,66,0,0,185,65,1,255,0,0,0,0]},"address":48529,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
Zigbee2MQTT:debug 2022-07-31 16:05:15: Received Zigbee message from 'Blinds - Back Lounge 3', type 'raw', cluster '64528', data '{"data":[13,99,18,108,128,97,0,0,0,0,2,0,0,192,39,18,66,0,0,185,65,1,255,0,0,0,0],"type":"Buffer"}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-07-31 16:05:15: No converter available for 'CP180335E-01' with cluster '64528' and type 'raw' and data '{"data":[13,99,18,108,128,97,0,0,0,0,2,0,0,192,39,18,66,0,0,185,65,1,255,0,0,0,0],"type":"Buffer"}'
```

**Comment by Koenkk** [comment]
To make sure the converter is loaded, I've added `CUSTOM` at the end of the description (https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1200117159). Can you load this external converter and see if `CUSTOM` appears at the end of the description when clicking on the device in the z2m frontend?

**Comment by shanelord01** [comment]
> To make sure the converter is loaded, I've added `CUSTOM` at the end of the description ([#359 (comment)](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1200117159)). Can you load this external converter and see if `CUSTOM` appears at the end of the description when clicking on the device in the z2m frontend?

Yes it is loading it:

```
Friendly name
Blinds - Back Lounge 1
Description
Last seen
N/A
Availability
Disabled
Device type
EndDevice
Zigbee Model
E-Wand
Zigbee Manufacturer
Current Products Corp
Description
Gen. 2 hybrid E-Wand CUSTOM
Support status
Supported

IEEE Address
0x847127fffe4cfa02
Network address
0x08DF
Manufacturer
Current Products Corp
Model
CP180335E-01
Power
Battery 47.5%
Interview completed
True
```

**Comment by shanelord01** [comment]
Also seeing this in the main Home Assistant logs:

2022-08-01 11:00:15 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): {"battery":47.5,"linkquality":255,"state":"OPEN","tilt":100}

**Comment by shanelord01** [comment]
So to test how ZHA does it I installed a seperate Zigbee stick and paired one of my ewand's to it. Here is the diagnostics output for it:

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Australia/Sydney",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.4",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "smartthinq_sensors": {
      "version": "0.23.6",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "chardet>=4.0.0"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "bureau_of_meteorology": {
      "version": "1.1.13",
      "requirements": [
        "iso8601"
      ]
    },
    "powercalc": {
      "version": "v0.24.5",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "tesla_custom": {
      "version": "2.3.1",
      "requirements": [
        "teslajsonpy==2.3.0"
      ]
    },
    "nest_protect": {
      "version": "0.3.8",
      "requirements": []
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "dwains_dashboard": {
      "version": "3.2.0",
      "requirements": []
    },
    "waste_collection_schedule": {
      "version": "1.24.0",
      "requirements": [
        "icalendar",
        "recurring_ical_events",
        "icalevents",
        "bs4"
      ]
    },
    "mila": {
      "version": "0.4.1",
      "requirements": [
        "milasdk==0.4.1",
        "python-benedict==0.24.3",
        "geopy==2.2.0",
        "python-aqi==0.6.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.31.1",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.77",
      "zigpy-deconz==0.18.0",
      "zigpy==0.47.3",
      "zigpy-xbee==0.15.0",
      "zigpy-zigate==0.9.0",
      "zigpy-znp==0.8.1"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 29203,
    "manufacturer": "Current Products Corp",
    "model": "E-Wand",
    "name": "Current Products Corp E-Wand",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4707,
    "power_source": "Battery or Unknown",
    "lqi": 255,
    "rssi": -65,
    "last_seen": "2022-08-01T23:45:08",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4707, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0202",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0020",
            "0x0102",
            "0x0b05",
            "0xfc10"
          ],
          "out_clusters": [
            "0x0003",
            "0x0019"
          ]
        }
      }
    },
    "entities": [
      {
        "entity_id": "button.current_products_corp_e_wand_02fa4cfe_identify",
        "name": "Current Products Corp E-Wand"
      },
      {
        "entity_id": "cover.current_products_corp_e_wand_02fa4cfe_window_covering",
        "name": "Current Products Corp E-Wand"
      },
      {
        "entity_id": "sensor.current_products_corp_e_wand_02fa4cfe_power",
        "name": "Current Products Corp E-Wand"
      },
      {
        "entity_id": "switch.current_products_corp_e_wand_02fa4cfe_on_off",
        "name": "Current Products Corp E-Wand"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "WINDOW_COVERING_DEVICE"
      }
    ],
    "user_given_name": "Blinds - Back Lounge 1",
    "device_reg_id": "c6d0809a8bd67cebe772dfe7d13c8f1c",
    "area_id": "back_lounge",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "WINDOW_COVERING_DEVICE",
          "id": 514
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "Current Products Corp"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "E-Wand"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 80
              },
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 95
              }
            },
            "unsupported_attributes": {
              "0x0031": {
                "attribute_name": "battery_size"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              }
            }
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 0
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_level",
                "value": 255
              }
            },
            "unsupported_attributes": {
              "0x4000": {
                "attribute_name": "start_up_current_level"
              },
              "0x0011": {
                "attribute_name": "on_level"
              },
              "0x0010": {
                "attribute_name": "on_off_transition_time"
              },
              "0x0012": {
                "attribute_name": "on_transition_time"
              },
              "0x0013": {
                "attribute_name": "off_transition_time"
              },
              "0x0014": {
                "attribute_name": "default_move_rate"
              }
            }
          },
          "0x0020": {
            "endpoint_attribute": "poll_control",
            "attributes": {
              "0x0000": {
                "attribute_name": "checkin_interval",
                "value": 13200
              }
            },
            "unsupported_attributes": {}
          },
          "0x0102": {
            "endpoint_attribute": "window_covering",
            "attributes": {
              "0x0009": {
                "attribute_name": "current_position_tilt_percentage",
                "value": 100
              }
            },
            "unsupported_attributes": {
              "0x0008": {
                "attribute_name": "current_position_lift_percentage"
              }
            }
          },
          "0x0b05": {
            "endpoint_attribute": "diagnostic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfc10": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

**Comment by Koenkk** [comment]
Looking at your logs `{"battery":47.5,"linkquality":255,"state":"OPEN","tilt":100}` looks correct to me. (`state` is now `OPEN`). Isn't this reflected in HA?

**Comment by shanelord01** [comment]
> Looking at your logs `{"battery":47.5,"linkquality":255,"state":"OPEN","tilt":100}` looks correct to me. (`state` is now `OPEN`). Isn't this reflected in HA?

No this is not populating the Home Assistant state.

**Comment by Koenkk** [comment]
@shanelord01 I've updated https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1200117159 to use `open`/`closed`

**Comment by shanelord01** [comment]
> @shanelord01 I've updated [#359 (comment)](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1200117159) to use `open`/`closed`

In the Z2M "State" submenu for the blind it still shows:

{
    "battery": 47.5,
    "linkquality": 255,
    "state": "OPEN",
    "tilt": 100
}

Even with the updated code. Seems something in Z2M is capitalising it.

**Comment by Koenkk** [comment]
What happens if you manually publish to `zigbee2mqtt/YOUR_DEVICE_FRIENDLY_NAME` payload `{"battery":48,"linkquality":255,"state":"open","tilt":100}`? If this doesn't give the correct state this looks a HA issue to me.

**Comment by shanelord01** [comment]
Nothing changes. But if I look at the device in HA only attributes for battery, link quality and tilt are shown. State is either not being passed to or not being received by HA.

**Comment by shanelord01** [comment]
OK.

I just took [this advice](https://github.com/Koenkk/zigbee2mqtt/issues/9604#issuecomment-997322634) to test it and put this in my HA configuration.yaml

This test blind is presenting HA with a state. Is there any way to make Z2M present the same to HA?

mqtt:
  cover:
    - name: "Test Blinds"
      json_attributes_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      position_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      position_template: "{{ value_json.tilt }}"
      set_position_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set/tilt"
      command_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set/tilt"
      position_open: 100
      position_closed: 0
      payload_open: "100"
      payload_close: "0"
      payload_stop: "STOP"

**Comment by Koenkk** [comment]
@shanelord01 this looks a bit of a hack for me since we map position to tilt, nevertheless, does it full work now without any external converters?

**Comment by shanelord01** [comment]
It’s definitely a hack. It is working but I’ve actually disabled the entities provided by Z2M in HA and I’m using my created one which is not ideal at all as it doesn’t fix the problem (ie ideally whatever I’m doing should be done in Z2M or others will have the same issue). 

Without this HomeKit and Google Home etc don’t work when using Home Assistant to bridge to them.

**Comment by Koenkk** [comment]
I think we should first try to solve this at the HA side because I feel this workaround should be implemented there (since it is exposing to HomeKit/Google Home). Can you make an issue in the HA issue tracker?

**Comment by shanelord01** [comment]
With all due respect,  I don’t believe it’s a Home Assistant issue. 

The fact I can access the raw mqtt info (from the device presented into mqtt by Z2M with my manual mqtt cover in HA) shows the data is available - just the way Z2M is presenting it into HA auto discovery is incorrect.

I don’t know how the Z2M to HA auto discovery works behind the scenes - but that is where I believe the issue is.

**Comment by Koenkk** [comment]
> just the way Z2M is presenting it into HA auto discovery is incorrect. 

In my opinion the way it exposes is correct, tilt is exposed as tilt, position as position. With https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1205953872 tilt is exposed as position which does not seem correct to me. 

My reason that this is a Home Assistant issue; Home Assistant is responsible for exposing the cover to Google Home/HomeKit. It seems it doesn't do this correct when the cover only supports tilt (in this case it should apply a workaround to expose the tilt as position) since Google Home/HomeKit don't support tilt.

**Comment by shanelord01** [comment]
> > just the way Z2M is presenting it into HA auto discovery is incorrect.
> 
> In my opinion the way it exposes is correct, tilt is exposed as tilt, position as position. With [#359 (comment)](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/359#issuecomment-1205953872) tilt is exposed as position which does not seem correct to me.
> 
> My reason that this is a Home Assistant issue; Home Assistant is responsible for exposing the cover to Google Home/HomeKit. It seems it doesn't do this correct when the cover only supports tilt (in this case it should apply a workaround to expose the tilt as position) since Google Home/HomeKit don't support tilt.

Take Google Home and HomeKit out of it - they are a symptom of the issue. 

The issue is Z2M is not updating HA state. That is the issue. Everything else stems from that.

**Comment by Koenkk** [comment]
With state you mean the `state` attribute right? Does it work with the following external converter and manual HA entry?

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    cover_position_tilt: {
        cluster: 'closuresWindowCovering',
        type: ['attributeReport', 'readResponse'],
        options: [exposes.options.invert_cover()],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            // Zigbee officially expects 'open' to be 0 and 'closed' to be 100 whereas
            // HomeAssistant etc. work the other way round.
            // For zigbee-herdsman-converters: open = 100, close = 0
            // ubisys J1 will report 255 if lift or tilt positions are not known, so skip that.
            const invert = model.meta && model.meta.coverInverted ? !options.invert_cover : options.invert_cover;
            if (msg.data.hasOwnProperty('currentPositionTiltPercentage') && msg.data['currentPositionTiltPercentage'] <= 100) {
                const value = msg.data['currentPositionTiltPercentage'];
                result.tilt = invert ? value : 100 - value;
                result.state = result.tilt === 0 ? 'CLOSE' : 'OPEN';
            }
            return result;
        },
    }
}

const tzLocal = {
    cover_position_tilt: {
        key: ['position', 'tilt'],
        options: [exposes.options.invert_cover()],
        convertSet: async (entity, key, value, meta) => {
            const isPosition = (key === 'position');
            const invert = !(utils.getMetaValue(entity, meta.mapped, 'coverInverted', 'allEqual', false) ?
                !meta.options.invert_cover : meta.options.invert_cover);
            const position = invert ? 100 - value : value;

            // Zigbee officially expects 'open' to be 0 and 'closed' to be 100 whereas
            // HomeAssistant etc. work the other way round.
            // For zigbee-herdsman-converters: open = 100, close = 0
            await entity.command(
                'closuresWindowCovering',
                isPosition ? 'goToLiftPercentage' : 'goToTiltPercentage',
                isPosition ? {percentageliftvalue: position} : {percentagetiltvalue: position},
                utils.getOptions(meta.mapped, entity),
            );

            return {state: {[isPosition ? 'position' : 'tilt']: value, state: value === 0 ? 'CLOSE' : 'OPEN'}};
        },
        convertGet: async (entity, key, meta) => {
            const isPosition = (key === 'position');
            await entity.read('closuresWindowCovering', [isPosition ? 'currentPositionLiftPercentage' : 'currentPositionTiltPercentage']);
        },
    }
}

const definition = {
    zigbeeModel: ['E-Wand'],
    model: 'CP180335E-01',
    vendor: 'Current Products Corp',
    description: 'Gen. 2 hybrid E-Wand CUSTOM',
    fromZigbee: [fzLocal.cover_position_tilt, fz.battery],
    toZigbee: [tz.cover_state, tzLocal.cover_position_tilt],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'closuresWindowCovering']);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.currentPositionTiltPercentage(endpoint);
    },
    exposes: [e.battery(), e.cover_tilt()],
};

module.exports = definition;
```


```yaml
mqtt:
  cover:
    - name: "Test Blinds"
      unique_id: xxx-xxx-xxx
      json_attributes_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      command_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set/state"
      state_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      value_template: "{{ value_json.state }}"
      state_open: "OPEN"
      state_closed: "CLOSE"
      tilt_command_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set/tilt"
      tilt_status_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      tilt_status_template: `{{ value_json.tilt }}`
```

**Comment by shanelord01** [comment]
Yes with this the "Test Blinds" shows correct state in Home Assistant.

"Blinds - Back Lounge 1" (auto-discovered) still shows "unknown" state in Home Assistant.

**Comment by Koenkk** [comment]
Great, can you remove the external converter and try with:

```yaml
mqtt:
  cover:
    - name: "Test Blinds"
      unique_id: xxx-xxx-xxx
      json_attributes_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      command_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set"
      state_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      value_template: "{% if value_json.tilt > 0 %} open {% else %} closed {% endif %}"
      tilt_command_topic: "zigbee2mqtt/Blinds - Back Lounge 1/set/tilt"
      tilt_status_topic: "zigbee2mqtt/Blinds - Back Lounge 1"
      tilt_status_template: `{{ value_json.tilt }}`
```

**Comment by shanelord01** [comment]
That works and shows correct state in HA.

Just FYI - I forgot to mention before that `{{ value_json.tilt }}` needs to be "{{ value_json.tilt }}" to work.

**Comment by Koenkk** [comment]
Great, I've pushed the fix for the auto discovery. Can you check if everything works? (without any external converter or HA config).

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by shanelord01** [comment]
Almost there! 

Now when tilt is showing closed/0 the open/close state is showing open. 

When tilt shows open/100 the open/close state is showing closed.

**Comment by Koenkk** [comment]
Pushed a possible fix, please check.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by digiblur** [comment]
I'll try this latest change as well as I noticed yesterday it was showing position 0 on my blinds/shades but still showing as Open on HA.  Rolled back my container to the latest tag for a quick fix until I had more time to investigate.

**Comment by digiblur** [comment]
Nope..

```json
{"battery":100,"last_seen":"2022-08-10T14:25:27-05:00","linkquality":98,"position":0,"state":"OPEN"}
```

**Comment by shanelord01** [comment]
> Pushed a possible fix, please check.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Hmmm - now running Zigbee2MQTT version 1.27.0-dev (commit #da4a3b9) and still seeing tilt showing open and state showing closed.

**Comment by Koenkk** [comment]
@digiblur with what device is this? Can you provide the debug log when closing/opening this device?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by digiblur** [comment]
> @digiblur with what device is this? Can you provide the debug log when closing/opening this device?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

I will fire up the container again. It was a few 3Reality sensors and one Phillips Hue motion sensor.

**Comment by digiblur** [comment]
> 

I see I responded to the wrong thread here.  This was with two different roller shade brands.  I'll pull them over to my dev container network as I had to stay on stable with my production box since this was messing up some automations showing the wrong closed/open states.  It's on the list for this weekend.

**Comment by digiblur** [comment]
> @digiblur with what device is this? Can you provide the debug log when closing/opening this device?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

@Koenkk 
I see I responded to the wrong thread here. This was with two different roller shade brands. I'll pull them over to my dev container network as I had to stay on stable with my production box since this was messing up some automations showing the wrong closed/open states. It's on the list for this weekend.

**Comment by digiblur** [comment]
ug 2022-08-27 23:26:52Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":92}' from endpoint 1 with groupID 0
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":96,"elapsed":1265,"last_seen":"2022-08-27T23:26:52-05:00","linkquality":149,"position":8,"state":"OPEN"}'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '96'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '8'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1265'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-27T23:26:52-05:00'
Info 2022-08-27 23:26:52MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '149'
Debug 2022-08-27 23:26:53Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":98}' from endpoint 1 with groupID 0
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":96,"elapsed":1265,"last_seen":"2022-08-27T23:26:54-05:00","linkquality":156,"position":2,"state":"OPEN"}'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '96'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '2'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1265'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-27T23:26:54-05:00'
Info 2022-08-27 23:26:53MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '156'
Debug 2022-08-27 23:26:54Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":100}' from endpoint 1 with groupID 0
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":96,"elapsed":1265,"last_seen":"2022-08-27T23:26:55-05:00","linkquality":149,"position":0,"state":"OPEN"}'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '96'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '0'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1265'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-27T23:26:55-05:00'
Info 2022-08-27 23:26:54MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '149'

**Comment by digiblur** [comment]
The state and control is correct in Zigee2MQTT itself but in HA it is no longer correct with the current Z2M dev container.

**Comment by Koenkk** [comment]
Can you post the debug log when fully closing it?

**Comment by digiblur** [comment]
> Can you post the debug log when fully closing it?

```Debug 2022-08-28 16:32:43Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":87}' from endpoint 1 with groupID 0
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":95,"elapsed":1264,"last_seen":"2022-08-28T16:32:43-05:00","linkquality":127,"position":13,"state":"OPEN"}'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '95'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '13'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-28T16:32:43-05:00'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '127'
Info 2022-08-28 16:32:43MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1264'
Debug 2022-08-28 16:32:44Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":93}' from endpoint 1 with groupID 0
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":95,"elapsed":1264,"last_seen":"2022-08-28T16:32:44-05:00","linkquality":134,"position":7,"state":"OPEN"}'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '95'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '7'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-28T16:32:44-05:00'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '134'
Info 2022-08-28 16:32:44MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1264'
Debug 2022-08-28 16:32:46Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":99}' from endpoint 1 with groupID 0
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":95,"elapsed":1265,"last_seen":"2022-08-28T16:32:45-05:00","linkquality":178,"position":1,"state":"OPEN"}'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '95'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '1'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-28T16:32:45-05:00'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '178'
Info 2022-08-28 16:32:46MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1265'
Debug 2022-08-28 16:32:47Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":100}' from endpoint 1 with groupID 0
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":95,"elapsed":1266,"last_seen":"2022-08-28T16:32:47-05:00","linkquality":145,"position":0,"state":"OPEN"}'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/battery', payload '95'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/position', payload '0'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/state', payload 'OPEN'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/last_seen', payload '2022-08-28T16:32:47-05:00'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/linkquality', payload '145'
Info 2022-08-28 16:32:47MQTT publish: topic 'zigbee2mqtt/YoolaxTest/elapsed', payload '1266'```

**Comment by Koenkk** [comment]
@digiblur pushed a possible fix, can you check again with the latest dev? If it doesn't work:
- provide me the debug log when fully closing and after that fully opening the cover
- what are the models of these devices?

**Comment by digiblur** [comment]
I'll give it a shot in a few hours... it happened on both of these device types

https://www.zigbee2mqtt.io/devices/WM25L-Z.html
https://www.zigbee2mqtt.io/devices/D10110.html

**Comment by Koenkk** [comment]
I'm really confused now, are you sure this is the latest dev?

https://github.com/Koenkk/zigbee2mqtt/commit/fa63ede uses zhc 14.0.608 which has the following logic: https://github.com/Koenkk/zigbee-herdsman-converters/blob/5ad7be2d69f371b170b5b0741e98d2e4579ea255/converters/fromZigbee.js#L1551

```js
                const value = msg.data['currentPositionLiftPercentage'];
                result[postfixWithEndpointName('position', msg, model, meta)] = invert ? value : 100 - value;
                if (!coverStateFromTilt) {
                    result[postfixWithEndpointName('state', msg, model, meta)] =
                        metaInvert ? (value === 0 ? 'CLOSE' : 'OPEN') : (value === 100 ? 'CLOSE' : 'OPEN');
                }
```

Your logs shows exactly the opposite, e.g.:

```
debug 2022-08-30 10:18:20: Received Zigbee message from 'YoolaxTest', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID 0
info  2022-08-30 10:18:20: MQTT publish: topic 'zigbee2mqtt/YoolaxTest', payload '{"battery":94,"elapsed":1255,"last_seen":"2022-08-30T10:18:20-05:00","linkquality":149,"position":100,"state":"CLOSE"}'
```

`value` = `currentPositionLiftPercentage` = `0`; `metaInvert  == false` for the `WM25L-Z` so the following logic applies: `(value === 100 ? 'CLOSE' : 'OPEN')` = `OPEN`, instead `CLOSE` is published in your case.  To be sure you are running the correct version, please update to the new z2m release version which will be released tomorrow.

**Comment by digiblur** [comment]
Yes. That was a copy and paste from the about screen. I pulled the latest update on docker before the test.

I will give it a shot tomorrow on my production network and rolling back is easy so no worries if it doesn't work. Bigger crowd to test with more covers anyways.

**Comment by digiblur** [comment]
Upgraded to the latest release on my production side and oddly my covers went to 0% as open, especially after forcing them to talk by adjusting the up/down.  Then after a couple minutes just as I was about to throw in the tag to roll back things.  They started popping back up as closed.   Super weird but at least it is working fine now. 

Caught one when before it updated back...

![image](https://user-images.githubusercontent.com/3240875/187935019-b318d334-669f-47b4-b0d7-d6c7047b1be3.png)

then after it corrected itself

![image](https://user-images.githubusercontent.com/3240875/187935054-e652d4c9-869e-438b-b71a-8e8bdfb08be3.png)

This was just in HA itself, states were showing correctly in Z2M.

**Comment by Koenkk** [comment]
@digiblur thats strange, but if I understand correctly, it works fine now?

**Comment by digiblur** [comment]
> @digiblur thats strange, but if I understand correctly, it works fine now?

Yep. Been working fine
