### ISSUE TITLE
HA-Update 2025.12.0: Zigbee2MQTT loosing connection every few minutes

### ISSUE THREAD

**Issue by luctv1** [zigbee2mqtt/hassio-zigbee2mqtt#830]
### Description of the issue

Hello,

I updated my HA to **2025.12.5b** and everything seemed fine and working.

Today I saw that all my Sensors which are connected with Sonoff Zigbee Sticks to Zigbee2MQTT, randomly loosing connection all at the same time for ~10sec and sometimes even for like 30mins. then they are reconnecting again.

The offical Update to 2025.12.0 came out and I installed it with the hope, that the issue will be solved.

But unfortunately the issue still remains. Has anyone experiencing this issue too. I've never had issues with my Zigbee Sensors and I think it has to do something with the Update oder Z2MQTT Software because all sensors loosing connection at the same time. 

### Addon version

v2.7.0

### Platform

Core: 2025.12.0
Supervisor: 2025.12.2
OS: 16.3

### Logs of the issue (if applicable)

[45df7312_zigbee2mqtt_2025-12-05T14-52-33.453Z.log](https://github.com/user-attachments/files/23963589/45df7312_zigbee2mqtt_2025-12-05T14-52-33.453Z.log)

**Comment by offsetkeyz** [comment]
I'm glad to see it's not just me

**Comment by luctv1** [comment]
> I'm glad to see it's not just me

I've found some new information for this problem. There are some compatibility issues with the stick for the latest version of Zigbee2MQTT. 

So just downgrade to the last version of Zigbee2MQTT and it will work again. I hope they will fix this soon.

Heres an other open issue: https://github.com/Koenkk/zigbee2mqtt/issues/29954

**Comment by offsetkeyz** [comment]
> So just downgrade to the last version of Zigbee2MQTT and it will work again. I hope they will fix this soon.

Are you running as an add-on? I'm having a hard time figuring out how to downgrade. It seems to only want me to install 2.7

**Comment by Nerivec** [comment]
@offsetkeyz try updating your adapter's firmware to 8.0.2:
https://github.com/Nerivec/silabs-firmware-builder/releases/tag/v2024.6.2-update7
It should eliminate the base of the timeout issues (contains several fixes on that point).

The issue linked above is about an I/O increase that caused problems in 2.7.0 with some networks (should be fixed in `dev`/`edge` for most cases): https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

**Comment by luctv1** [comment]
> > So just downgrade to the last version of Zigbee2MQTT and it will work again. I hope they will fix this soon.
> 
> Are you running as an add-on? I'm having a hard time figuring out how to downgrade. It seems to only want me to install 2.7

@offsetkeyz I just used a backup and only selected the Zigbee2MQTT Addon to backup. 

Or you can just upgrade the firmware of your stick like @Nerivec said. But thats just to complicated for me haha

**Comment by offsetkeyz** [comment]
Rolling back the version seems much less permanent than updating the firmware. Those zigbee sticks are finicky! Thank you both for the help though.

**Comment by Nerivec** [comment]
The Dongle-E was particularly affected by these timeout issues that the newer firmware fix. In case you still see issues, updating will be the only way to fix it completely (assuming there is no other factor at play like a bad power source or similar).

Note: you can upgrade and downgrade firmware on Silabs chips at will.

**Comment by offsetkeyz** [comment]
@luctv1 @Nerivec FWIW I updated the firmware on my dongle E and the problem persisted. After rolling back the version, it became stable again.

**Comment by Nerivec** [comment]
Did you try the hotfix release? 2.7.1 is out now.

**Comment by IAmWebSA** [comment]
See also Websocket Reconnecting... issue when triggering a z2m Backup via Addon.
Already at 2.7.1
